server:
  port: 8080
  host: 0.0.0.0

dfinity:
   canister: 22w4c-cyaaa-aaaab-qacka-cai  
   url: https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app
   
#   canister: rrkah-fqaaa-aaaaa-aaaaq-cai  
#   url: http://localhost:8000/   